# Streamlit Deployment Preparation

In [1]:
import pandas as pd

ranked_df = pd.read_csv(
    "../data/processed/explainable_candidate_ranking.csv"
)

ranked_df.head()

,ID,Resume_str,Resume_html,Category,Cleaned_Resume,Original_Length,Cleaned_Length,Semantic_Score,Matched_Skills,Skill_Match,Education_Match,Experience_Match,Final_Score,Missing_Skills,Explanation
0,29051656,INFORMATION TECHNOLOGY SPECIALIST ...,"<div class=""fontsize fontface vmargins hmargin...",INFORMATION-TECHNOLOGY,information technology specialist summary orga...,7133,5599,0.323972,"['aws', 'sql']",33.333333,0,50,32.771682,"['python', 'machine learning', 'deep learning'...",\n\nFinal Score: 32.77\n\nMatched Skills: 2\n\...
1,20824105,INFORMATION TECHNOLOGY AND AWS ADMIN ...,"<div class=""LCA skn-cbg1 fontsize fontface vma...",INFORMATION-TECHNOLOGY,information technology aws admin intern experi...,7380,5692,0.320266,"['python', 'aws']",33.333333,0,50,32.549283,"['machine learning', 'deep learning', 'tensorf...",\n\nFinal Score: 32.55\n\nMatched Skills: 2\n\...
2,12415691,INFORMATION DESIGNER Summary of...,"<div class=""fontsize fontface vmargins hmargin...",DESIGNER,information designer summary qualification str...,5421,4087,0.234243,"['python', 'sql']",33.333333,0,50,27.387944,"['machine learning', 'deep learning', 'tensorf...",\n\nFinal Score: 27.39\n\nMatched Skills: 2\n\...
3,16186411,DATABASE PROGRAMMER/ANALYST (.NET DEV...,"<div class=""fontsize fontface vmargins hmargin...",INFORMATION-TECHNOLOGY,database programmer analyst net developer summ...,9224,7031,0.276036,['sql'],16.666667,0,50,25.728812,"['python', 'machine learning', 'deep learning'...",\n\nFinal Score: 25.73\n\nMatched Skills: 1\n\...
4,26746496,DATABASE PROGRAMMER/ANALYST (.NET DEV...,"<div class=""fontsize fontface vmargins hmargin...",INFORMATION-TECHNOLOGY,database programmer analyst net developer summ...,8535,6390,0.273252,['sql'],16.666667,0,50,25.561766,"['python', 'machine learning', 'deep learning'...",\n\nFinal Score: 25.56\n\nMatched Skills: 1\n\...

# Select Columns For Streamlit Dashboard

In [2]:
dashboard_df = ranked_df[
    [
        "ID",
        "Category",
        "Final_Score",
        "Matched_Skills",
        "Missing_Skills",
        "Explanation"
    ]
]

dashboard_df.head()

,ID,Category,Final_Score,Matched_Skills,Missing_Skills,Explanation
0,29051656,INFORMATION-TECHNOLOGY,32.771682,"['aws', 'sql']","['python', 'machine learning', 'deep learning'...",\n\nFinal Score: 32.77\n\nMatched Skills: 2\n\...
1,20824105,INFORMATION-TECHNOLOGY,32.549283,"['python', 'aws']","['machine learning', 'deep learning', 'tensorf...",\n\nFinal Score: 32.55\n\nMatched Skills: 2\n\...
2,12415691,DESIGNER,27.387944,"['python', 'sql']","['machine learning', 'deep learning', 'tensorf...",\n\nFinal Score: 27.39\n\nMatched Skills: 2\n\...
3,16186411,INFORMATION-TECHNOLOGY,25.728812,['sql'],"['python', 'machine learning', 'deep learning'...",\n\nFinal Score: 25.73\n\nMatched Skills: 1\n\...
4,26746496,INFORMATION-TECHNOLOGY,25.561766,['sql'],"['python', 'machine learning', 'deep learning'...",\n\nFinal Score: 25.56\n\nMatched Skills: 1\n\...

# Save Dashboard Dataset

In [3]:
dashboard_df.to_csv(
    "../data/processed/dashboard_data.csv",
    index=False
)

print("Dashboard dataset saved successfully.")

Dashboard dataset saved successfully.

In [4]:
print(dashboard_df.shape)

(500, 6)